# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply 2 numbers
#' @param x, first number
#' @param y, second number
multiplyy <- function(x, y) {
    .Call(`_rschnel_multiplyy`, x, y)
}

